added an option connect_environment
alexherbo2/connect.kak pull request #9
Opened 2020-02-20 14:18 UTC by listentolist

The option connect_envrionment is evaluated just after the .env files,
so that the user can change and set environment variables in the connected
shell through this option.

2020-02-20 14:56 UTC, alexherbo2 requested changes

2020-02-20 14:56 UTC, alexherbo2 commented on rc/connect.kak
> +declare-option str connect_environment ""
Quotes are optional.

2020-02-20 14:56 UTC, alexherbo2 commented on rc/connect.kak
> +      eval $kak_opt_connect_environment
Should be quoted.

2020-02-20 14:56 UTC, alexherbo2 commented on rc/connect.kak
> +      eval $kak_opt_connect_environment
Should be quoted.

2020-02-20 14:59 UTC, alexherbo2 commented
Can you document the feature to make it discoverable?

2020-02-21 10:54 UTC, alexherbo2 commented
Looks good.

Can you squash the commits into a single one and add before the copyright waiver?

2020-02-21 16:55 UTC, listentolist commented
Alright. I already added the copyright waiver some days ago. [https://github.com/alexherbo2/connect.kak/commit/9e318bd5dce583cb29d112fba474aac645daf7e7](url)

2020-02-21 17:26 UTC, merged